feature: switch to agentops api v2
AgentOps-AI/agentops pull request #209
Opened 2024-05-16 00:49 UTC by siyangqiu

## 📥 Pull Request

**📘 Description**
DRAFT: AgentOps API v2 is WIP. 

Changes endpoints to use the newer AgentOps v2 API, which is much faster than the v1 endpoints

2024-05-16 02:06 UTC, HowieG requested changes

2024-05-16 02:06 UTC, HowieG commented on agentops/__init__.py
> +    if os.getenv('AGENTOPS_LOGGING_LEVEL') == 'DEBUG':
Add to env.example

2024-05-16 02:06 UTC, HowieG commented on agentops/__init__.py
> +import logging
Do we need to import logging?

2024-05-16 06:36 UTC, HowieG requested changes

2024-05-16 06:36 UTC, HowieG commented on agentops/client.py
> +            print('Could not determine cost of run.')
Update to logger.info

2024-05-16 06:36 UTC, HowieG commented on agentops/client.py
> +            print('\nThis run cost ${}'.format('{:.2f}'.format(
Update to logger.info. Remove \n

2024-05-17 21:21 UTC, siyangqiu commented on agentops/__init__.py
> +    if os.getenv('AGENTOPS_LOGGING_LEVEL') == 'DEBUG':
We don't have one and no one will see it if we do because they will install the package and it will end up in site-packages

2024-05-17 21:22 UTC, siyangqiu commented on agentops/__init__.py
> +import logging
Yes and no. We can avoid importing it if we create a bunch of separate functions inside the logger and export those. This is probably better

2024-05-18 02:50 UTC, HowieG approved these changes

2024-05-24 20:44 UTC, merged