Added session link to end_session
AgentOps-AI/agentops pull request #213
Opened 2024-05-17 01:52 UTC by HowieG

2024-05-17 06:59 UTC, areibman commented on agentops/client.py
> +                        logger.warning(f"🖇️ AgentOps: Failed to set up autogen logger with AgentOps. Error: {e}")
Uppercase Autogern

2024-05-17 07:00 UTC, areibman requested changes

2024-05-17 07:00 UTC, areibman commented on agentops/client.py
> +        logger.info('View info on this session at https://app.agentops.ai/drilldown?session_id=%s',
`This run's cost`

2024-05-17 07:01 UTC, areibman requested changes, later dismissed

2024-05-17 07:01 UTC, areibman commented on agentops/client.py
> +        logger.info('View info on this session at https://app.agentops.ai/drilldown?session_id=%s',
Just use an `f""` string

2024-05-22 19:46 UTC, siyangqiu approved these changes

2024-05-22 22:12 UTC, merged