check ao version and warn for update
AgentOps-AI/agentops pull request #326
Opened 2024-08-01 20:55 UTC by bboynton97

On `.init()` checks if the agentops version is out of date and if it is, logs a warning.

2024-08-01 21:07 UTC, bboynton97 commented
Closes ENG-465

2024-08-01 23:56 UTC, HowieG requested changes

2024-08-01 23:56 UTC, HowieG commented on agentops/helpers.py
> +                f" WARNING: {parts[0]} is out of date. Please update with the command: 'pip install --upgrade {parts[0]}'"
can we just do pip install --upgrade agentops so it's more clear what this does

2024-08-02 00:11 UTC, HowieG approved these changes

2024-08-02 00:11 UTC, merged