liteLLM bug
AgentOps-AI/agentops pull request #476
Opened 2024-10-31 16:18 UTC by sarath59

## 📥 Pull Request

**📘 Description**

The problem occurs because:
1. When both libraries are imported, the override methods are competing for the same OpenAI completion methods
2. LiteLLM internally uses OpenAI's format, and when both are imported, the overrides are interfering
3. The global variables storing original methods are being overwritten

**🧪 Testing**

Test Coverage
1. Synchronous and asynchronous API calls
2. Streaming and non-streaming responses
3. Method override and restoration
4. Error handling and logging
5. Multiple consecutive API calls
6. Integration with LiteLLM present

Validation Results
1. Successfully tracked OpenAI API calls with LiteLLM imported
2. Properly handled method overrides and restorations
3. Maintained compatibility with both sync and async operations
4. Verified proper error handling and logging
5. Confirmed session management and cleanup
![Screenshot 2024-10-31 at 11 16 41 AM](https://github.com/user-attachments/assets/846fcea4-2d96-4fc1-9df4-529f26c53fe7)
![Screenshot 2024-10-31 at 11 17 28 AM](https://github.com/user-attachments/assets/ffe58549-6749-4c4d-a5f6-f82aa61b021b)

2024-11-01 01:39 UTC, areibman commented
Yo @sarath59 ! Looks like someone else raised the same PR at the same time you did haha. Figuring out which one we should go with/merge both

2024-11-01 01:53 UTC, sarath59 commented
I was rechecking the code again and again because of the conflicts. No worries.

2024-11-06 17:04 UTC, sarath59 commented
Hey @areibman , did you get a chance to look at this PR? Let me know if you want me to close this one if you moved forward with other PR. Thanks

2024-11-06 20:29 UTC, areibman commented
This works, thanks @sarath59!
<img width="957" alt="image" src="https://github.com/user-attachments/assets/463689e1-de25-47a5-84f1-0c8480136f6d">

```In [7]: client = openai.OpenAI()

In [8]: message = [{"role": "user", "content": "Write a 12 word poem about secret agents."}]

In [9]: litellm.completion(model="claude-3-sonnet-20240229", messages=message, temperature=0)
Out[9]: ModelResponse(id='chatcmpl-7f8c0a42-a784-44ce-a3fc-673feb469dcf', choices=[Choices(finish_reason='stop', index=0, message=Message(content="Here's a 12 word poem about secret agents:\n\nShadows lurk, secrets kept,\nAgents slink, missions adept.\nDanger's thrill, adrenaline rush,\nCovert ops, whispers hushed.", role='assistant', tool_calls=None, function_call=None))], created=1730924756, model='claude-3-sonnet-20240229', object='chat.completion', system_fingerprint=None, usage=Usage(completion_tokens=61, prompt_tokens=18, total_tokens=79, completion_tokens_details=None, prompt_tokens_details=PromptTokensDetailsWrapper(audio_tokens=None, cached_tokens=0, text_tokens=None, image_tokens=None), cache_creation_input_tokens=0, cache_read_input_tokens=0))

In [10]: client.chat.completions.create(model="gpt-4o", messages=message, temperature=0)
Out[10]: ChatCompletion(id='chatcmpl-AQgtGVEgUBeZytGKDD8PwHhlsaQvG', choices=[Choice(finish_reason='stop', index=0, logprobs=None, message=ChatCompletionMessage(content='In shadows they move, whispers of truth, cloaked in mystery, unseen guardians.', refusal=None, role='assistant', audio=None, function_call=None, tool_calls=None))], created=1730924762, model='gpt-4o-2024-08-06', object='chat.completion', service_tier=None, system_fingerprint='fp_159d8341cc', usage=CompletionUsage(completion_tokens=17, prompt_tokens=17, total_tokens=34, completion_tokens_details=CompletionTokensDetails(audio_tokens=0, reasoning_tokens=0, accepted_prediction_tokens=0, rejected_prediction_tokens=0), prompt_tokens_details=PromptTokensDetails(audio_tokens=0, cached_tokens=0)))

In [11]: agentops.end_session("Success")
🖇 AgentOps: This run's cost $0.001182
🖇 AgentOps: Session Replay: https://app.agentops.ai/drilldown?session_id=76796998-df08-415c-aa5e-1993e101f1ed
```

Leaving some comments on the PR. I know @teocns and @the-praxs have some thoughts also

2024-11-06 20:46 UTC, sarath59 commented
Thanks @areibman

2024-11-06 20:49 UTC, areibman requested changes

2024-11-06 20:49 UTC, areibman commented on agentops/llm_tracker.py
I think we have a merge conflict-- can you merge with the current changes in main?

2024-11-06 20:49 UTC, areibman commented on tests/test_llmintegration.py
> +load_dotenv()
We are running tests through `tox` (`pip install tox` and run `tox` in the CLI to spin up all the tests). We're failing right now because of dotenv

2024-11-06 20:49 UTC, areibman commented on agentops/llm_tracker.py
> +                    continue  # Continue to check other APIs instead of returning
Nice

2024-11-06 20:49 UTC, areibman commented on tests/test_llmintegration.py
I would move + rename this file as a core manual test. We don't do unit tests for libraries right now (i.e. OpenAI, Anthropic, Litellm) although we could in the future.

Since this makes an outbound connection, the test would fail in an offline environment.

2024-11-06 20:54 UTC, teocns commented on tests/test_llmintegration.py
@areibman let's change that

2024-11-06 20:56 UTC, the-praxs commented on tests/test_llmintegration.py
+1

2024-11-06 21:13 UTC, areibman commented on tests/test_llmintegration.py
<img width="251" alt="image" src="https://github.com/user-attachments/assets/aaacdf74-04d0-4cd9-acd2-0605afca40dc">
i.e. move it to this folder. Also, when you include the `test_` prefix, it will get caught by pytest, so we should rename the file

2024-11-06 21:20 UTC, teocns commented on tests/test_llmintegration.py
I'll fix that for @sarath59

2024-11-07 00:00 UTC, teocns commented
[Added](https://github.com/sarath59/agentops/blob/liteLLMbug/AgentOps/tests/test_llmintegration.py#L83C1-L96C51) VCR for offline replay and changed a bit the test dynamics to be more deterministic, however this still fails for me and does not send openai events to agentops dashboard's session replay either 🤔 

```

@pytest.mark.vcr
def test_openai_litellm_tango(llm_event_spy, openai_client, litellm_client):
    """Test that LiteLLM integration does not break OpenAI from sending events"""
    message = [{"role": "user", "content": "Write a 3 word sentence."}]

    litellm_client.completion(
        model="claude-3-sonnet-20240229", messages=message, temperature=0
    )

    assert llm_event_spy["litellm"].call_count == 1

    openai_client.chat.completions.create(
        model="gpt-4", messages=message, temperature=0
    )

    assert llm_event_spy["openai"].call_count == 1

```

Maybe something slipped under my eye, or maybe it has to do with the order of iimport/nitialization

```
FAILED tests/test_llmintegration.py::test_openai_litellm_tango - assert 0 == 1
```

`litellm` passes, `openai` not

2024-11-18 12:43 UTC, teocns commented
the branch behind this PR was 150-180 commits behind before recently rebasing; something must've got in between. From internal discussions it emerged that now-deprecated `LLMTracker` interfering might be the actual issue

2024-11-21 01:23 UTC, closed without merging