Added basic integration with LangGraph
AgentOps-AI/agentops pull request #501
Opened 2024-11-11 11:33 UTC by SoumilRathi

# Basic Integration with LangGraph

## Description

This PR introduces an integration with LangGraph agents by adding a callback handler to use with LangGraph agents and multi-agent systems. This allows for basic logging of LangGraph agents and their systems.

## Key Features

### `LanggraphCallbackHandler` class

- Introduces a callback handler class to use with LangGraph agents and multi-agent systems
- Implements functions for all event types as given in the BaseCallbackHandler for LangGraph

### Testing

-  Added a multi-agent system test for the LangGraph callback handler
- The test covers tool use, actions, and LLM responses, to allow an extensive testing coverage

## Testing Instructions

1. Ensure that the following environment variables are set: 
- OPENAI_API_KEY
- AGENTOPS_API_KEY

2. Run the test case using:
`
python tests/langgraph_handlers/_test_langgraph_handler.py
`

## Notes

- The LangGraph callback handler is effectively just the LangChain wrapper with the unimplemented functions added. I chose to create it as a separate file so as to not interfere with the LangChain integration

## Potential Improvements

- The completion for agents in a multi-agent system in LangGraph is unreliable (the response for each llm call is noted as tool use instead of a completion/response). This might be something to resolve before 
- The UI for function calling and prompting on the Session Reply and Chat Viewer could be improved - either with better categorization in the callback handler or specific UI changes in the frontend. 
- A finished stream still displays as Indeterminate on the AgentOps dashboard - perhaps this could be changed to "Success" on agent finish.

2024-11-13 07:37 UTC, areibman commented
Super cool, thank for raising @SoumilRathi ! Will take a look

2024-11-14 11:55 UTC, the-praxs commented
@SoumilRathi thanks for the PR! I see that its working but I noticed 2 LLMEvents for the same conversation as denoted by the ChatViewer -
<img width="1817" alt="image" src="https://github.com/user-attachments/assets/dd897683-bade-48b1-8069-752db1b877cf">

First LLMEvent -
<img width="1064" alt="image" src="https://github.com/user-attachments/assets/7119e20c-13e3-45d4-887d-6afdf58b4667">

Second LLMEvent -
<img width="1043" alt="image" src="https://github.com/user-attachments/assets/91f2600a-8c7d-4e85-9110-0830225ddc04">

This is the code I used to test (adapted from [Langfuse](https://langfuse.com/docs/integrations/langchain/example-python-langgraph)):

```python
from typing import Annotated
import agentops
from dotenv import load_dotenv
import os

from langchain_openai import ChatOpenAI
from langchain_core.messages import HumanMessage
from typing_extensions import TypedDict
 
from langgraph.graph import StateGraph
from langgraph.graph.message import add_messages

from agentops.partners.langgraph_callback_handler import LanggraphCallbackHandler
 
load_dotenv()
agentops.init(api_key=os.getenv("AGENTOPS_API_KEY"), default_tags=["langgraph-test-v1"])
 
class State(TypedDict):
    # Messages have the type "list". The `add_messages` function in the annotation defines how this state key should be updated
    # (in this case, it appends messages to the list, rather than overwriting them)
    messages: Annotated[list, add_messages]
 
graph_builder = StateGraph(State)
 
llm = ChatOpenAI(model = "gpt-4o", temperature = 0.2)
 
# The chatbot node function takes the current State as input and returns an updated messages list. This is the basic pattern for all LangGraph node functions.
def chatbot(state: State):
    return {"messages": [llm.invoke(state["messages"])]}
 
# Add a "chatbot" node. Nodes represent units of work. They are typically regular python functions.
graph_builder.add_node("chatbot", chatbot)
 
# Add an entry point. This tells our graph where to start its work each time we run it.
graph_builder.set_entry_point("chatbot")
 
# Set a finish point. This instructs the graph "any time this node is run, you can exit."
graph_builder.set_finish_point("chatbot")
 
# To be able to run our graph, call "compile()" on the graph builder. This creates a "CompiledGraph" we can use invoke on our state.
graph = graph_builder.compile()
 
# Initialize AgentOps CallbackHandler for Langchain (tracing)
handler = LanggraphCallbackHandler()
 
for s in graph.stream({"messages": [HumanMessage(content = "What is Langfuse?")]},
                      config={"callbacks": [handler]}):
    print(s)
```

I would request you to resolve this issue and also create an example notebook having different examples (say the code like above and a more complex agent architecture) to check if everything's working.

2024-11-14 12:30 UTC, the-praxs requested changes
This works but its better to make these changes to ensure consistency.

2024-11-14 12:30 UTC, the-praxs commented on agentops/partners/langgraph_callback_handler.py
> +                instrument_llm_calls=False,
Add `default_tags` here.

2024-11-14 12:30 UTC, the-praxs commented on agentops/partners/langgraph_callback_handler.py
> +                instrument_llm_calls=False,
Add `default_tags` here.

2024-11-14 12:30 UTC, the-praxs commented on agentops/partners/langgraph_callback_handler.py
> +                    event.completion_tokens = response.llm_output["token_usage"].get("completion_tokens")
These should have default values for safety if the attributes are absent.

2024-11-14 12:30 UTC, the-praxs commented on agentops/partners/langgraph_callback_handler.py
> +                params=kwargs,
`logs` or `details` not `params`.

2024-11-14 12:30 UTC, the-praxs commented on agentops/partners/langgraph_callback_handler.py
> +                params=kwargs,
`logs` or `details` not `params`.

2024-11-14 12:30 UTC, the-praxs commented on agentops/partners/langgraph_callback_handler.py
> +                params=kwargs,
`logs` or `details` not `params`.

2024-11-14 12:30 UTC, the-praxs commented on agentops/partners/langgraph_callback_handler.py
> +                params=kwargs
`logs` or `details` not `params`.

2024-11-14 12:30 UTC, the-praxs commented on agentops/partners/langgraph_callback_handler.py
> +    def _get_event_or_create_error(
This function should be defined outside the class to work with both the `LanggraphCallbackHandler` and `AsyncLanggraphCallbackHandler`.

2024-11-14 12:30 UTC, the-praxs commented on agentops/partners/langgraph_callback_handler.py
> +    def _cleanup_event(self, event_dict: Dict[str, Any], run_id: UUID) -> None:
This function should be defined outside the class to work with both the `LanggraphCallbackHandler` and `AsyncLanggraphCallbackHandler`.

2024-11-14 12:30 UTC, the-praxs commented on agentops/partners/langgraph_callback_handler.py
> +                    event.completion_tokens = response.llm_output["token_usage"].get("completion_tokens")
These should have default values for safety if the attribute is absent.

2024-11-14 12:33 UTC, dot-agi commented
@SoumilRathi I have tested the `_test_langgraph_handler.py` and the same issues with `LLMEvent` are present here -

* First event - 
<img width="1615" alt="image" src="https://github.com/user-attachments/assets/f97f0cd7-e522-4cfb-aaf6-97189c459d0f">

* Second event -
<img width="1308" alt="image" src="https://github.com/user-attachments/assets/1226a113-b0ee-4093-b621-0604a80c0594">

Please resolve the inconsistencies in the ChatML format for the `prompt` and `completions` to ensure everything is looking correct -
<img width="1808" alt="image" src="https://github.com/user-attachments/assets/c06832d0-850e-4041-84e1-f4f64b99e9f0">

2025-01-05 00:11 UTC, closed without merging