Added More Indepth Tool Documentation For Anthropic API
AgentOps-AI/agentops pull request #503
Opened 2024-11-11 19:14 UTC by TKTSWalker

## 📥 Pull Request

**📘 Description**

1. Made an example showcasing simple tool calling while showing a second which showcased both using multiple calls at once and requesting an input
2. Left code blocks which could be used for listening for a singular tool or multiple
3. Showed how to initialize the tools and give the data to the LLM as context
4. Reflected as such within the Anthropic general guide journal 

**🧪 Testing**
The major outputs are still visible with their results intact within the journal!

Also on the journal for the barebones reference, it might be a good idea to remove the tool segment and point to the document! Finally, it might be good to make a third link on the readme page with a link to the journal itself although you may already have plans here!

2024-11-11 19:20 UTC, TKTSWalker commented
@the-praxs All done! The main file referenced is [here!](https://github.com/TKTSWalker/agentops/blob/main)

2024-11-12 02:33 UTC, TKTSWalker commented
#499

2024-11-12 02:33 UTC, TKTSWalker commented
#499

2024-11-12 12:42 UTC, TKTSWalker commented
Fix bug https://github.com/AgentOps-AI/agentops/issues/499

2024-11-12 12:43 UTC, TKTSWalker commented
Fix bug #499

2024-11-13 07:36 UTC, areibman requested changes
Handful of changes. Also can we rename the notebook or combine it with another one? We have several example notebooks in this examples directory that more or less do the same things

2024-11-13 07:36 UTC, areibman commented on examples/anthropic_examples/agentops-anthropic-understanding-tools.ipynb
<img width="954" alt="image" src="https://github.com/user-attachments/assets/d3415259-c07b-40ec-8bf3-8a00d0592e56">
Can we make this cell smaller? The example, although creative, is a bit too long to illustrate the point we're demonstrating

2024-11-13 07:36 UTC, areibman commented on examples/anthropic_examples/agentops-anthropic-understanding-tools.ipynb
Minor idiomatic python nit:
```
print (tool_use_count)
```
No space between print and `(`

```

while loop < tool_use_count: #We will get the tools now
    tool_use_block = response.content[loop + 1] #We start at 1 since 0 holds the AI mesage
    tool_name = tool_use_block.name
    tool_input = tool_use_block.input
    
    if tool_name == "inventoryscan_tool":
        # Call the inventoryscan function for inventoryscan_tool
        invscanres = inventoryscan()
    elif tool_name == "enemyscan_tool":
        # Get the amount for enemyscan_tool
        amount = tool_input['amount']
        # Call the enemyscan function with the amount
        enemyscanres = enemyscan(amount)
        
    loop = loop + 1 
```

This is a pretty uncommon way to loop in python. I'd recommend a for loop:
```
for _ in range(tool_use_count):
    ...
```


```
invscanres = ""
enemyscanres = ""
```
snake_case for readability 
```
inv_scan_res = ""
enemy_scan_res = ""
initial_messages
```

2024-11-13 07:36 UTC, areibman commented on examples/anthropic_examples/agentops-anthropic-understanding-tools.ipynb
<img width="367" alt="image" src="https://github.com/user-attachments/assets/645cd6f7-a764-42c7-abaf-aa244f99365a">
Extra markdown cell not deleted

2024-11-13 07:36 UTC, areibman commented on examples/anthropic_examples/agentops-anthropic-understanding-tools.ipynb
Print the content `response.content`
<img width="586" alt="image" src="https://github.com/user-attachments/assets/53f47f30-80d5-4a2e-8044-a79892befbba">

2024-11-13 07:36 UTC, areibman commented on examples/anthropic_examples/agentops-anthropic-understanding-tools.ipynb
TitleCase is reserved for classes in python
```
CombatCasualties 
Missions 
```
```
combat_casualties
missions 
```

2024-11-13 11:46 UTC, TKTSWalker commented on examples/anthropic_examples/agentops-anthropic-understanding-tools.ipynb
Hello, many apologies! I'll keep the below in mind when making more journals in the future! I would suggest renaming the notebook rather than combining it with another, the reason mainly being the ways in which the tools are extracted! In specific, the system loops through each "block" in order to get the appropriate data in relation to the tool that should be used!

Shortening the example, I went overkill admittedly!

2024-11-13 11:48 UTC, TKTSWalker commented on examples/anthropic_examples/agentops-anthropic-understanding-tools.ipynb
I purposefully didn't use the for loop as when originally using it, I had an error related to the first content block (Which from what I can tell is always the AI dialogue), so instead I had to work outside the box!
Basically we get the amount of times the word ToolBlock appears right (Because it will always appear just once unless the user does something that has it appear many times)! Then if we start loop on 0, we can just add a value of 1 (To account for the first item basically not being readable)! Then as soon as loop is greater than the amount of times the item appears we know that we are out of range!
Thinking about it, it could technically be possible to turn each chunk into a sort of string list and then remove the first chunk like that but i'm not %100 sure if it'd be worth it (I'm still willing to if you believe it is)!

Fixing variables, that is something else I should've fixed!

Same with TitleCase, a bad habit from my C# naming shenanigans

2024-11-13 11:48 UTC, TKTSWalker commented on examples/anthropic_examples/agentops-anthropic-understanding-tools.ipynb
Deleting extra markdown cell!

2024-11-13 11:48 UTC, TKTSWalker commented on examples/anthropic_examples/agentops-anthropic-understanding-tools.ipynb
It will be fixed!

2024-11-15 14:32 UTC, TKTSWalker reviewed
Good to go!

2024-11-15 14:33 UTC, TKTSWalker commented
Sorry for the small time gap, was preoccupied with my own project for a little! I've updated the journal, if there are any more problems please feel free to let me know!

2024-11-19 08:26 UTC, areibman approved these changes

2024-11-19 08:26 UTC, merged

2024-11-19 08:26 UTC, areibman commented
Thanks for the PR @TKTSWalker !

2024-11-19 13:14 UTC, TKTSWalker commented
No problem, looking forward to doing more!