Added simple Ollama example
AgentOps-AI/agentops pull request #515
Opened 2024-11-18 18:25 UTC by akhilbandhu

## 📥 Pull Request

**📘 Description**
Added an ollama example to satisfy Issue 460 https://github.com/AgentOps-AI/agentops/issues/460

**🧪 Testing**
Made sure build succeeds

2024-11-19 08:15 UTC, areibman requested changes
Very minor changes, but overall looks great!

2024-11-19 08:15 UTC, areibman commented on examples/ollama_examples/ollama_examples.ipynb
<img width="985" alt="image" src="https://github.com/user-attachments/assets/a56ef719-f8de-4c39-9fe6-8f87b26b8107">

Either only run `agentops.init()` without `agentops.start_session()` or run `agentops.init(auto_start_session=False)` plus `agentops.start_session()`

2024-11-19 08:15 UTC, areibman commented on examples/ollama_examples/ollama_examples.ipynb
<img width="494" alt="image" src="https://github.com/user-attachments/assets/a4e5807f-df01-4ea5-88bc-065cb3b1ac74">
2 things:
1. Restart the kernel and run from top to bottom to ensure it works. Here, the first cell is `[14]` which may indicate the notebook state is wrong
2. Can you clear the outputs from the install cell before committing the save? Makes the notebook easier to read

2024-11-19 08:17 UTC, areibman requested changes

2024-11-19 08:17 UTC, areibman commented on docs/v1/examples/examples.mdx
Can you create a custom examples page? You can look at the LangChain example as a start.

You probably wouldn't know this, but we have a tool that dynamically injects the outputs of the example notebook into the page. i.e.
<img width="610" alt="image" src="https://github.com/user-attachments/assets/8c606be0-08e4-41d9-b2b1-46a5c9c0ab76">

2024-11-20 01:48 UTC, akhilbandhu commented on docs/v1/examples/examples.mdx
@areibman Sure I can do that, what is the name of the tool you mentioned? Didn't want to go around replicating work

2024-11-20 04:38 UTC, areibman commented on docs/v1/examples/examples.mdx
Including the line `{/*    SOURCE_FILE: ...` should do the trick. You can copy the LangChain example .mdx file and use that as the starting point

2024-11-20 05:31 UTC, akhilbandhu commented on docs/v1/examples/examples.mdx
Cool beans, I am assuming that that will only run when this is merged with main? Looks like it's a Github action

2024-11-22 07:30 UTC, akhilbandhu commented on docs/v1/examples/examples.mdx
Actually was able to figure out the nbconvert tool and got it working! @areibman Let me know what you think

2024-11-22 22:41 UTC, areibman approved these changes
Awesome!!

2024-11-22 22:43 UTC, merged