[Docs] OpenAI Integration docs for the website
AgentOps-AI/agentops pull request #549
Opened 2024-12-05 14:06 UTC by the-praxs

## 📥 Pull Request

**📘 Description**
* Closes #470 and #548 
* Adds a doc page for OpenAI with sync and async example codes for both streaming and non-streaming
* Minor changes to Anthropic and Cohere docs

**🧪 Testing**
* Previewed with mvintlify locally for the docs
* Tested the code examples locally

**🗒️ TODO**
* Add sections for `openai<1.0.0` and `openai>=1.0.0`
* Add example notebook(s) for OpenAI similar to Anthropic
* Add a link in the `examples/README.md`

2024-12-05 22:00 UTC, the-praxs commented
@areibman should I include a link to the example notebooks in the docs page?

2024-12-06 04:27 UTC, areibman requested changes

2024-12-06 04:27 UTC, areibman commented on docs/v1/integrations/openai.mdx
> +      <img height="200" src="https://github.com/AgentOps-AI/agentops/blob/cf67191f13e0e2a09446a61b7393e1810b3eee95/docs/images/link-to-session.gif?raw=true" />
Can we kill the gif? Replace with a screenshot.

Also, instead of having the hash `.../blob/abc123...` make it point to `.../blob/main/`

2024-12-06 04:30 UTC, areibman commented on docs/v1/integrations/openai.mdx
> +      <img height="200" src="https://github.com/AgentOps-AI/agentops/blob/cf67191f13e0e2a09446a61b7393e1810b3eee95/docs/images/link-to-session.gif?raw=true" />
Nvm just did it

2024-12-06 04:44 UTC, areibman approved these changes

2024-12-06 04:44 UTC, merged