Update AG2 Reference
AgentOps-AI/agentops pull request #602
Opened 2024-12-23 09:56 UTC by yiranwu0

## 📥 Pull Request

**📘 Description**
_Briefly describe the changes you've made._

Package `pyautogen` is now associated with the repo renamed to AG2. This PR reflects the changes in AgentOps.

**🧪 Testing**
_Describe the tests you performed to validate your changes._

2025-01-04 10:19 UTC, the-praxs requested changes
Left some comments, please revert.

2025-01-04 10:19 UTC, the-praxs commented on docs/v1/examples/examples.mdx
> +  <Card title="AG2" icon={<img src="https://raw.githubusercontent.com/ag2ai/ag2/refs/heads/main/website/logo/ag2.svg" alt="AG2"/>} iconType="image" href="/v1/integrations/autogen">
Logo is very small and unclear.

<img width="117" alt="image" src="https://github.com/user-attachments/assets/434b5111-d88f-44b3-861d-57e8ed14dc52" />

2025-01-04 10:19 UTC, the-praxs commented on docs/v1/usage/sdk-reference.mdx
> +[ag2](/v1/integrations/autogen)) to stop using AgentOps' auto-instrumentation of LLM libraries such as OpenAI. This
**AG2** instead of **ag2**

2025-01-08 13:48 UTC, yiranwu0 commented on docs/v1/usage/sdk-reference.mdx
> +[ag2](/v1/integrations/autogen)) to stop using AgentOps' auto-instrumentation of LLM libraries such as OpenAI. This
Updated

2025-01-08 13:49 UTC, yiranwu0 commented on docs/v1/examples/examples.mdx
> +  <Card title="AG2" icon={<img src="https://raw.githubusercontent.com/ag2ai/ag2/refs/heads/main/website/logo/ag2.svg" alt="AG2"/>} iconType="image" href="/v1/integrations/autogen">
I updated the figure pointing to a svg created in this folder and changed the color. Please let me know if this still doesn't work!

2025-01-08 13:51 UTC, the-praxs approved these changes

2025-01-08 13:51 UTC, merged