[Feat] OpenAI Assistants (Beta) Integration
AgentOps-AI/agentops pull request #609
Opened 2024-12-28 18:31 UTC by the-praxs

# 📥 [Feat] OpenAI Assistants (Beta) Integration

Closes #482. Adds support for the [OpenAI Assistants API](https://platform.openai.com/docs/api-reference/assistants).

Supports the following APIs -
* Assistants
* Threads
* Messages
* Runs
* Run Steps

## Changelog 
TBA

2024-12-31 04:43 UTC, areibman requested changes

2024-12-31 04:43 UTC, areibman commented on docs/v1/integrations/openai.mdx
> +<script type="modue" src="/scripts/github_stars.js"></script>
Typo

2024-12-31 13:17 UTC, the-praxs commented on docs/v1/integrations/openai.mdx
> +<script type="modue" src="/scripts/github_stars.js"></script>
yikes

2025-01-04 04:56 UTC, areibman commented
<img width="1334" alt="image" src="https://github.com/user-attachments/assets/22d301c8-4f6b-45be-978a-784a8f43d921" />
Nailed it! Let's merge

2025-01-04 04:57 UTC, areibman approved these changes

2025-01-04 04:57 UTC, merged