Multi-
AgentOps-AI/agentops pull request #91
Opened 2024-02-29 01:26 UTC by bboynton97

## 📥 Pull Request

**📘 Description**
Briefly describe the changes you've made.

**🔄 Related Issue (if applicable)**
If this PR is related to an existing issue, reference it here.

**🎯 Goal**
Explain the intention behind this change.

**🔍 Additional Context**
Any extra information or context to help us understand the change?

**🧪 Testing**
Describe the tests you performed to validate your changes.

Thank you for your contribution to Agentops!

2024-03-03 00:28 UTC, areibman requested changes

2024-03-03 00:28 UTC, areibman commented on examples/multi-agent.ipynb
<img width="1066" alt="image" src="https://github.com/AgentOps-AI/agentops/assets/14807319/a0cae591-50d4-4f96-bb12-1ffc59ad95f0">
Please re-run the notebook. First cell should be `[1]`. Also, there is a giant error

2024-03-03 00:28 UTC, areibman commented on examples/multi-agent.ipynb
Nit: This is the more pythonic way to do this:
`OPENAI_API_KEY = os.environ.get('OPENAI_API_KEY', "<your_api_key")`
<img width="665" alt="image" src="https://github.com/AgentOps-AI/agentops/assets/14807319/0276335d-b323-4132-96ae-c1bb521301d2">
The second arg will be taken if the variable is not found

2024-03-03 00:28 UTC, areibman commented on examples/multi-agent.ipynb
<img width="954" alt="image" src="https://github.com/AgentOps-AI/agentops/assets/14807319/2630c631-81f6-4e1a-80a6-276d8ab46256">
* Remove endpoint arg. Users don't need to see this
* You're probably using openai version 0.2x.xx. Upgrade to 1.x.x+

2024-03-03 00:28 UTC, areibman commented on agentops/worker.py
<img width="498" alt="image" src="https://github.com/AgentOps-AI/agentops/assets/14807319/0f4fff65-f096-4e4b-87ba-a4b543835819">
We're moving towards the Otel way of tracking agents. We don't want to be in the business of creating our own framework, so let's not do this

2024-03-03 00:28 UTC, areibman commented on agentops/agent.py
> +            return generator()
This is copied from `llm_tracker.py`, no? Why not update that instrumentor instead?

2024-03-03 00:28 UTC, areibman commented on agentops/agent.py
> +class Agent:
We need to have a longer discussion about the implementation pattern. I'd prefer to not have strongly opinionated agent classes if we can help it-- we should try to rely on 3rd party instrumentors and lightweight decorators/context managers (`with`)

2024-03-08 20:34 UTC, bboynton97 commented
Abandoned in favor of a better design

2024-03-08 20:34 UTC, closed without merging