Readme error log consent
AgentOps-AI/agentops pull request #96
Opened 2024-03-01 21:50 UTC by bboynton97

![image](https://github.com/AgentOps-AI/agentops/assets/6846214/efc73e42-de65-4028-9aa9-b98b0787f21c)

Mostly generated by GPT. The key points are that we adhere to CCPA requirements and that the SDK is subject to our Privacy Policy.

2024-03-01 21:54 UTC, siyangqiu approved these changes
One comment, otherwise, good to me

2024-03-01 21:54 UTC, siyangqiu commented on README.md
> +_By implementing this SDK, you acknowledge and agree that the SDK may automatically send error reports to our servers. These reports are strictly limited to information relevant for identifying and r
This may or may not be true depending on what the stack traces contain. Maybe say that this information will only be used by us

2024-03-02 00:05 UTC, siyangqiu commented on README.md
> +_By implementing this SDK, you acknowledge and agree that the SDK may automatically send error reports to our servers. These reports are strictly limited to information relevant for identifying and r
Specifically referencing: "No personal information or sensitive data will be transmitted as part of these reports without your explicit consent."

2024-03-03 00:29 UTC, areibman requested changes
Let's have a `TOS.md` instead of putting this in `README.md`

2024-03-14 21:21 UTC, areibman commented
> Let's have a `TOS.md` instead of putting this in `README.md`

I looked at some other repos, and TOS is not a common readme (sorry for the misleading suggestion). Let's keep these changes though; I've raised an issue to the  documentation repository in the meantime.

2024-03-14 21:21 UTC, areibman approved these changes
Thanks Braelyn :)

2024-03-14 21:23 UTC, merged